### ISSUE TITLE
[Bug] get wrong stream position while get "FileHeader" stream in ".hwp" file

### ISSUE THREAD

**Issue by sboh1214** [CoreOffice/OLEKit#1]
Hello, I'm using OLEKit with hwp file which use in Korea.
It has stream "FileHeader" with fixed size 256 bytes.
However, OLEKit throws uncaught error Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
when I try to get data of stream by readDataToEnd()

```swift
let positiveURL = URL(fileURLWithPath: #file)
        .deletingLastPathComponent()
        .appendingPathComponent("SampleHwp")
        .appendingPathComponent("blank.hwp")
let ole = try OLEFile(positiveURL.path)
let fileHeaderStream = ole.root.children.first(where: { $0.name == "FileHeader"})!
let reader = try ole.stream(fileHeaderStream)
let data = reader.readDataToEnd()
```
You can also find this code snippet in my repo [sboh1214/HwpKit](https://github.com/sboh1214/HwpKit/blob/22acd2cd382783d8c792570023ec84300d8e61c4/Tests/HwpKitTests/HwpKitTests.swift#L27)

In hex, stream "FileHeader" should read as ascii (about in position 16112)

> 48 57 50 20 44 6F 63 75 6D 65 6E 74 20 46 69 6C 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 04 03 00 05
> HWP Document File ................ 4 3 0 5 (version codes of hwp file) --> Omitted below

Overall, thanks for your library!

**Comment by MaxDesiatov** [comment]
Thanks for checking out this library! If I understand correctly, in `HwpKit` in `HwpFileHeader` initializer you're trying to read the signature, but there isn't enough data in the corresponding `DataReader`. Here on the screenshot `byteOffset` is already 255, but you're trying to read 32 more bytes, and the total length of `data` is 256 bytes.

<img width="858" alt="Screenshot 2020-09-14 at 14 03 46" src="https://user-images.githubusercontent.com/112310/93089367-1cadd080-f693-11ea-9bb8-a2c8009f7231.png">

Thanks for pointing me to this issue, `DataReader` should check for the length by itself. I'll add preconditions to `DataReader` to make this error obvious.

**Comment by MaxDesiatov** [comment]
Also, the error is specifically in this snippet in `HwpFileHeader`:

```swift
        data = dataReader.readDataToEnd()
        signature = String(data: dataReader.readData(ofLength: 32), encoding: .utf16LittleEndian) ?? "Error"
```

You've used `readDataToEnd()` once, which set the `byteOffset` value (the reading "cursor") to the end of the stream. There's nothing left to read, so you can't use `readData` again on this stream unless you use `seek` to rewind the reading position to somewhere else where data is available. Or maybe you need to create a different stream from other entry altogether to get the data you're looking for, I don't know the details of your format to say for sure.

Does that resolve your issue?

**Comment by sboh1214** [comment]
Thank you for your kind answer and for investigating my error!
However, there is one more question as I wrote above.

I open this file with ole-py, which is another ole/com tool written in python.
You can see code in this repo.
[https://github.com/sboh1214/ole-py/blob/master/test.py](https://github.com/sboh1214/ole-py/blob/master/test.py)

As a result, the "FileHeader" stream of .hwp file starts with the signature "HWP Document File" encoded with ASCII.

> ('FileHeader', 'DocInfo', '\x05HwpSummaryInformation', 'PrvImage', 'PrvText', 'Scripts/JScriptVersion', 'Scripts/DefaultJScript', 'DocOptions/_LinkDoc', 'BinData/BIN0001.png', 'BodyText/Section0')
========================================
HWP Document File

However, when I use OLEKit, I have a result below.
[https://github.com/sboh1214/HwpKit/blob/646014bb13910badc6f4dbc6cc88589d249495dd/Tests/HwpKitTests/HwpKitTests.swift#L35](https://github.com/sboh1214/HwpKit/blob/646014bb13910badc6f4dbc6cc88589d249495dd/Tests/HwpKitTests/HwpKitTests.swift#L35)

> Optional("´¥\0­\u{14}zøÄf\"\u{12}ÍAtgu9¹\u{19}>\u{1E}\u{1D}W\u{1A}\rñ£")

Can you help me what is wrong? Sorry for using the infamous file format :)

**Comment by MaxDesiatov** [comment]
Thanks for the update, this looks like a bug to me, I'm investigating now...
