### ISSUE TITLE
.doc file is in ole object format, but without EncryptionInfo

### ISSUE THREAD

**Issue by imbears** [CoreOffice/OLEKit#14]
.doc file is in ole object format, but without EncryptionInfo

**Comment by imbears** [comment]
How to judge encryption?

**Comment by MaxDesiatov** [comment]
Hi, I'm not sure what you're referring to from the limited information you've provided. Would you be able to provide more details and self-contained example code to reproduce the issue? Thanks!

**Comment by ii00ii** [comment]
do {
            guard let path = Bundle.main.path(forResource: "noencryption", ofType: "doc") else { return }
           let ole = try OLEFile(path)
            print(ole.root.children)
        } catch {
            print(error)
        }

log:
[OLEKit.DirectoryEntry(name: "Data", type: OLEKit.StorageType.stream, leftIndex: 4294967295, rightIndex: 4294967295, childIndex: 4294967295, firstStreamSector: 8, streamSize: 4096, children: []), OLEKit.DirectoryEntry(name: "\u{01}CompObj", type: OLEKit.StorageType.stream, leftIndex: 4294967295, rightIndex: 4294967295, childIndex: 4294967295, firstStreamSector: 0, streamSize: 110, children: []), OLEKit.DirectoryEntry(name: "1Table", type: OLEKit.StorageType.stream, leftIndex: 1, rightIndex: 6, childIndex: 4294967295, firstStreamSector: 16, streamSize: 6867, children: []), OLEKit.DirectoryEntry(name: "\u{05}SummaryInformation", type: OLEKit.StorageType.stream, leftIndex: 4294967295, rightIndex: 4294967295, childIndex: 4294967295, firstStreamSector: 30, streamSize: 4096, children: []), OLEKit.DirectoryEntry(name: "\u{05}DocumentSummaryInformation", type: OLEKit.StorageType.stream, leftIndex: 4, rightIndex: 4294967295, childIndex: 4294967295, firstStreamSector: 38, streamSize: 4096, children: []), OLEKit.DirectoryEntry(name: "WordDocument", type: OLEKit.StorageType.stream, leftIndex: 2, rightIndex: 5, childIndex: 4294967295, firstStreamSector: 0, streamSize: 4096, children: [])]

**Comment by imbears** [comment]
code:

```swift
do {
      guard let path = Bundle.main.path(forResource: "noencryption", ofType: "doc") else { return }
      let ole = try OLEFile(path)
      print(ole.root.children)
} catch {
      print(error)
}
```

log:
[
OLEKit.DirectoryEntry(name: "Data", type: OLEKit.StorageType.stream, leftIndex: 4294967295, rightIndex: 4294967295, childIndex: 4294967295, firstStreamSector: 8, streamSize: 4096, children: []), 

OLEKit.DirectoryEntry(name: "\u{01}CompObj", type: OLEKit.StorageType.stream, leftIndex: 4294967295, rightIndex: 4294967295, childIndex: 4294967295, firstStreamSector: 0, streamSize: 110, children: []), 

OLEKit.DirectoryEntry(name: "1Table", type: OLEKit.StorageType.stream, leftIndex: 1, rightIndex: 6, childIndex: 4294967295, firstStreamSector: 16, streamSize: 6867, children: []), 

OLEKit.DirectoryEntry(name: "\u{05}SummaryInformation", type: OLEKit.StorageType.stream, leftIndex: 4294967295, rightIndex: 4294967295, childIndex: 4294967295, firstStreamSector: 30, streamSize: 4096, children: []), 

OLEKit.DirectoryEntry(name: "\u{05}DocumentSummaryInformation", type: OLEKit.StorageType.stream, leftIndex: 4, rightIndex: 4294967295, childIndex: 4294967295, firstStreamSector: 38, streamSize: 4096, children: []), 

OLEKit.DirectoryEntry(name: "WordDocument", type: OLEKit.StorageType.stream, leftIndex: 2, rightIndex: 5, childIndex: 4294967295, firstStreamSector: 0, streamSize: 4096, children: [])
]

**Comment by MaxDesiatov** [comment]
Thanks for sharing the code snippet. If you're looking for `EncryptionInfo` in an unencrypted `.doc` file, I'm not sure it's an issue with OLEKit per se. Could you clarify what exactly you're trying to do and what you're looking for, in what context?

**Comment by imbears** [comment]
Thanks.
I want to take fEncrypted and fObfuscated to determine whether the file is encrypted.

**Comment by MaxDesiatov** [comment]
But if `fEncrypted` and `fObfuscated` aren't present, doesn't it mean that the file is certainly unencrypted?

**Comment by imbears** [comment]
<img width="653" alt="截屏2022-08-18 15 14 16" src="https://user-images.githubusercontent.com/53004655/185333177-0a7fd566-6d9b-43b9-b77a-7fa7aeeb6b8b.png">

**Comment by MaxDesiatov** [comment]
Thanks for sharing this. I'm still not sure I understand what's the issue with OLEKit library that you're having? The purpose of this library is to parse raw OLE format. Parsing of `.doc` files and any specifics of that format should be resolved by other libraries built on top of OLEKit, not OLEKit itself, unless can provide sample code that reproduces a bug or specifies a feature request within the scope of this library.
