### ISSUE TITLE
[Bug] Storage & Stream Structure is Different while testing .hwp file

### ISSUE THREAD

**Issue by sboh1214** [CoreOffice/OLEKit#6]
hello!

When I read the official document and investigate the storage and stream structure with OLE/COM viewer in Windows,
it is like the picture below.

* Here is repo link [https://github.com/tyranid/oleviewdotnet](https://github.com/tyranid/oleviewdotnet)

<img alt="화면 캡처 2020-09-18 165636" src="https://user-images.githubusercontent.com/30364442/93577656-42aadc00-f9d7-11ea-9137-17b6fd2d7259.png">

However, when I add a breakpoint and get the structure of ole with your OLEKit, it is like below.

* I add a breakpoint in [Sources/HwpKit/HwpFile.swift#L19](https://github.com/sboh1214/HwpKit/blob/6e247a0731d017473dbdfe46821cdc8edf8eb778/Sources/HwpKit/HwpFile.swift#L19) and investigated let ole.

<img width="344" alt="스크린샷 2020-09-18 오후 5 41 44" src="https://user-images.githubusercontent.com/30364442/93577587-3030a280-f9d7-11ea-9eff-15ca4d76aa3c.png">

Could you explain why these two results are different? Thanks :)

**Comment by MaxDesiatov** [comment]
Hi @sboh1214, I'm not sure why the structure is different. The algorithm in OLEKit is modeled after the [olefile](https://github.com/decalage2/olefile) Python library. If you expand children of those nodes, you see that all of the nodes are available, it's just child-parent relationship is somewhat different in oleviewdotnet, I've not sure why they implemented it differently.

<img width="387" alt="Screenshot 2020-09-18 at 11 52 23" src="https://user-images.githubusercontent.com/112310/93589866-6c4b0f80-f9a5-11ea-9d49-f0196c646791.png">

Is there a document anywhere that could clarify which of the possible children-parent structures is the correct one? I assume, if you use only OLEKit and rely on its structure, it shouldn't be a problem, would that work for you?

**Comment by sboh1214** [comment]
Thanks for replying @MaxDesiatov !

Get the right structure of ole storage is a pretty important part in reading hwp file.
So, I also try using olefile in my test repo. However, it shows the same result with oleviewdotnet, different from OLEKit.

Here is the result of [sboh1214/ole-py/test.py](https://github.com/sboh1214/ole-py/blob/93f5297db471b411b70ad4027fc4ed69786a750d/test.py#L1)

<img width="349" alt="스크린샷 2020-09-19 오전 10 07 32" src="https://user-images.githubusercontent.com/30364442/93655674-f061cd80-fa5f-11ea-8274-eae1382b3353.png">

Also, I will add the screenshot of the official document. Unfortunately, it does not have an English version :(

<img width="716" alt="스크린샷 2020-09-19 오전 10 11 56" src="https://user-images.githubusercontent.com/30364442/93655780-8dbd0180-fa60-11ea-8352-9b452311126d.png">

Sorry, cause I don't know about the internal manipulating of ole/com object, I cannot help you a lot...

**Comment by MaxDesiatov** [comment]
Thanks for comparing the entries, this is very helpful! I guess there's a bug in [the `children` property parsing code](https://github.com/CoreOffice/OLEKit/blob/6a809b91a9a524594c02d990dbce157d7e9cb447/Sources/OLEKit/DirectoryEntry.swift#L125), I'll be able to have a closer look next week, I hope that's not a big problem.

**Comment by MaxDesiatov** [comment]
This should now be resolved in `main` and will be released in the next version. Please feel free to reopen if you still see any problems. Thanks again for reporting the bug!
