### ISSUE TITLE
Request Publishing New Version

### ISSUE THREAD

**Issue by sboh1214** [CoreOffice/OLEKit#8]
Hi, thanks for patching the bug so fast!
Would you publish the new version of olekit?
As below picture, it can be used as version without versioning your library.
It would be great if you add a version that applies bug fix.

<img width="1792" alt="스크린샷 2020-09-29 오후 9 18 11" src="https://user-images.githubusercontent.com/30364442/94557680-d8791d80-0299-11eb-87df-630915c1b291.png">

**Comment by MaxDesiatov** [comment]
Hi @sboh1214, thanks for raising the issue. 0.2.0 has been tagged now, feel free to reopen or create a new one if you see any problems. 🙂
